"""
house_model.py — Tier 2 projections for all 435 House districts.

WHAT CHANGED FROM TIER 1
------------------------
Tier 1 covered only polled districts and refused to say anything about the
other ~396. Tier 2 gives every district a projection by falling back to a
structural lean, exactly as senate_model.py already does for unpolled states.
Two mechanisms, one formula:

    polled district:    LEAN_ALPHA_HOUSE * poll_avg + (1-alpha) * lean  + econ + appr
    unpolled district:                                        lean     + econ + appr

The second is the first with the poll term unavailable. Rows carry has_polls
so display can tell them apart instead of dressing structural guesses up as
polled projections.

WHAT TIER 2 STILL DOES NOT DO
-----------------------------
  * NO chamber-control probability IN THIS FILE. 435 point estimates are not a
    control call — that needs a Monte Carlo over correlated district errors.
    This file reports seat COUNTS only; monte_carlo_house.py turns them into
    probabilities and owns the correlation structure and the per-district error
    sigmas (which differ for polled vs lean-only districts).
  * NO generic ballot term. 538's generic-ballot feed is dead (its polls-page
    CSVs all return HTML now), so the national environment reaches these
    projections only through climate_adjustment and approval_adjustment, which
    are national by construction. A real generic-ballot term would replace
    neither — it would sit alongside them.
  * NO incumbency for unrostered districts. house_nominees.csv covers ~83
    districts; the other ~350 have no known incumbent, so their flip status is
    unknowable and is reported as False rather than guessed. Seat-count deltas
    against the current chamber are therefore not available here.

BIAS LEDGER
-----------
The lean under ~396 of these districts is 538's 2022-vintage partisan lean —
2016/2020 presidential results on 2022 maps. It contains no 2024, and for the
95 districts in redrawn states it describes boundaries that no longer exist
(see fetch_district_lean.py, which prints them on every run). Unpolled
projections are therefore materially weaker than polled ones, and weakest of
all in TX/NC/OH/FL. The honest read: this file now covers the chamber, but
coverage is not accuracy.
"""

import csv
import os

from init_db import get_connection
from senate_model import (
    weighted_average_and_stderr,
    get_climate_score, climate_adjustment,
    get_approval_score, approval_adjustment,
    _finalize_race,
)
from house_ingest import load_house_nominees, _pad

LEAN_ALPHA_HOUSE = 0.80   # matches senate_model.LEAN_ALPHA; (1-alpha) is the lean weight

DISTRICT_LEAN_PATH = os.path.join(os.path.dirname(__file__), "data", "district_lean.csv")

GENERIC_NAME = {"D": "Democratic candidate", "R": "Republican candidate"}


def load_district_lean(path=DISTRICT_LEAN_PATH):
    """
    Read data/district_lean.csv into {(state, district): dem_margin}.

    Generated by fetch_district_lean.py — a missing file is a setup error, not
    a data gap, so it raises rather than silently degrading all 435 districts
    to neutral (which would look like a working model producing 50-50 ties).
    """
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"{path} not found — run fetch_district_lean.py first."
        )

    lean = {}
    with open(path, newline="") as f:
        for row in csv.DictReader(f):
            key = (row.get("district") or "").strip().upper()
            margin = (row.get("dem_margin") or "").strip()
            if not key or not margin:
                continue
            state, _, district = key.partition("-")
            lean[(state, _pad(district))] = float(margin)
    return lean


def district_lean_baseline(state, district, party, district_lean):
    """
    Structural baseline as a vote-share %, from the stored signed margin.
    Same derivation as senate_model.lean_baseline:
        margin = dem_share - rep_share = 2*dem_share - 100  ->  dem_share = margin/2 + 50

    An unknown district returns 50.0 (neutral, no structural pull) rather than
    raising — house.csv occasionally polls a district that district_lean.csv
    has never heard of, and a neutral baseline is the right answer there.
    """
    margin = district_lean.get((state, district))
    if margin is None:
        return 50.0

    dem_share = 50.00 + margin / 2.00
    rep_share = 50.00 - margin / 2.00
    if party == "D":
        return dem_share
    if party == "R":
        return rep_share
    return 50.0   # independents: no structural lean data exists at district level


def predict_house_races(year=2026):
    roster, _skipped = load_house_nominees()
    district_lean = load_district_lean()
    climate  = get_climate_score(year)
    approval = get_approval_score(year)

    con = get_connection()
    cur = con.cursor()
    cur.execute(
        "SELECT id, state, district FROM races WHERE year = ? AND district != ''",
        (year,),
    )
    races = cur.fetchall()

    results = []
    for race_id, state, district in races:
        finalists = []
        parties = [p for (s, d, p) in roster if s == state and d == district]
        incumbent_party = next(
            (p for p in parties if roster[(state, district, p)].get("is_incumbent")), ""
        )

        for party in parties:
            info = roster[(state, district, party)]
            cur.execute(
                "SELECT id FROM candidates WHERE race_id = ? AND name = ?",
                (race_id, info["name"]),
            )
            row = cur.fetchone()
            if not row:
                continue                     # nominee never appeared in polls — skip (scripture rule)
            poll_avg, poll_stderr = weighted_average_and_stderr(race_id, row[0])
            if poll_avg is None:
                continue

            econ = climate_adjustment(party, climate)
            appr = approval_adjustment(party, approval)
            lean = district_lean_baseline(state, district, party, district_lean)
            blended   = LEAN_ALPHA_HOUSE * poll_avg + (1 - LEAN_ALPHA_HOUSE) * lean
            projected = round(blended + econ + appr, 2)

            finalists.append({
                "state": state, "district": district,
                "race": f"{state}-{district}",
                "name": info["name"], "party": party,
                "poll_avg": poll_avg, "econ": econ, "appr": appr,
                "lean": round(lean, 2),
                "projected": projected,
                "poll_stderr": poll_stderr,
                "has_polls": True,
                "is_incumbent": info.get("is_incumbent", False),
                "incumbent_party": incumbent_party,
                "incumbent_known": bool(incumbent_party),
            })

        # A one-sided polled race is a data gap, not a contest — discard it and
        # let the lean-only pass below rebuild the district coherently.
        if len(finalists) < 2:
            continue

        results.extend(_finalize_race(finalists))

    con.close()

    # ---- Lean-only pass: every district without a poll-based projection -----
    # Runs over district_lean.csv's key set, which IS the 435-district universe.
    # Names come from the roster when it has them (a rostered-but-unpolled
    # district has real nominees) and are generic otherwise.
    projected = {(r["state"], r["district"]) for r in results}

    for (state, district) in sorted(district_lean):
        if (state, district) in projected:
            continue

        incumbent_party = next(
            (p for p in ("D", "R")
             if roster.get((state, district, p), {}).get("is_incumbent")), ""
        )

        finalists = []
        for party in ("D", "R"):
            info = roster.get((state, district, party), {})
            lean = district_lean_baseline(state, district, party, district_lean)
            econ = climate_adjustment(party, climate)
            appr = approval_adjustment(party, approval)
            finalists.append({
                "state": state, "district": district,
                "race": f"{state}-{district}",
                "name": info.get("name") or GENERIC_NAME[party],
                "party": party,
                "poll_avg": None, "econ": econ, "appr": appr,
                "lean": round(lean, 2),
                "projected": round(lean + econ + appr, 2),
                "poll_stderr": None,
                "has_polls": False,
                "is_incumbent": info.get("is_incumbent", False),
                "incumbent_party": incumbent_party,
                # Unrostered districts have no known incumbent, so _finalize_race
                # will report is_flip=False. That is "unknown", not "hold".
                "incumbent_known": bool(incumbent_party),
            })

        results.extend(_finalize_race(finalists))

    return results, climate, approval


if __name__ == "__main__":
    results, climate, approval = predict_house_races()

    print(f"Climate score: {climate:+.3f} · Approval score: {approval:+.2f}")
    print(f"Tier 2 — all districts projected; polled and lean-only marked separately\n")

    polled_races = {r["race"] for r in results if r["has_polls"]}

    def print_section(rows, heading):
        """
        Print one basis section: districts grouped by race, alphabetical.

        Sorting on the "XX-NN" race key orders by state abbreviation first and
        district second, and house_ingest._pad already zero-pads the district
        so '02' sorts before '10' — the reason districts are stored as padded
        text in the first place.

        Poll-backed and lean-only rows print different detail fields because
        they carry different information: a lean-only row has no poll average
        and no stderr, and padding it with placeholders would make a structural
        guess look like a thin poll.
        """
        print(f"\n{'═'*70}\n{heading}\n{'═'*70}")
        if not rows:
            print("  (none)")
            return

        current = None
        for r in sorted(rows, key=lambda x: x["race"]):
            if r["race"] != current:
                current = r["race"]
                print(f"\n── {current} ──────────────")
            marker = "★" if r.get("winner") else " "
            inc    = " [incumbent]" if r["is_incumbent"] else ""
            flip   = " ⚡FLIP" if r.get("winner") and r.get("is_flip") else ""
            tossup = " 🪙TOSSUP" if r.get("winner") and r.get("is_tossup") else ""
            if r["has_polls"]:
                detail = f"poll: {r['poll_avg']:.1f}% ±{r['poll_stderr']:.1f}%  lean: {r['lean']:.1f}%"
            else:
                detail = f"lean-only: {r['lean']:.1f}%"
            print(f"  {marker} {r['party']}  {r['name']:<28} {detail}  "
                  f"econ: {r['econ']:+.2f}pp  appr: {r['appr']:+.2f}pp  → {r['projected']:.1f}%{inc}{flip}{tossup}")

    polled    = [r for r in results if r["has_polls"]]
    lean_only = [r for r in results if not r["has_polls"]]

    print_section(polled, f"POLLED DISTRICTS — {len(polled_races)} districts")

    # Lean-only districts are computed and COUNTED, just not itemized: 399
    # per-candidate breakdowns would restate district_lean.csv at length and
    # bury the ~36 districts that carry actual poll information. They still
    # flow into the seat totals below — which is the whole point of Tier 2, so
    # the summary reports the polled/lean-only split on every line rather than
    # letting the suppressed rows disappear from view.
    lean_only_races = {r["race"] for r in lean_only}
    if lean_only_races:
        print(f"\n{len(lean_only_races)} lean-only district(s) not itemized above, "
              f"included in the seat counts below.")

    winners = [r for r in results if r.get("winner")]
    d_leads = sum(1 for r in winners if r["party"] == "D")
    r_leads = sum(1 for r in winners if r["party"] == "R")
    d_polled = sum(1 for r in winners if r["party"] == "D" and r["has_polls"])
    r_polled = sum(1 for r in winners if r["party"] == "R" and r["has_polls"])
    tossups  = sum(1 for r in winners if r.get("is_tossup"))

    print(f"\n{'─'*62}")
    print(f"  Districts projected: {len(winners)}   "
          f"(polled: {len(polled_races)}  ·  lean-only: {len(winners) - len(polled_races)})")
    print(f"  D leads: {d_leads}  (polled {d_polled}, lean-only {d_leads - d_polled})")
    print(f"  R leads: {r_leads}  (polled {r_polled}, lean-only {r_leads - r_polled})")
    print(f"  Toss-ups: {tossups}")
    print(f"\n  Seat COUNTS only — not a control probability. Lean-only districts")
    print(f"  rest on 2022-vintage lean; see the bias ledger at the top of this file.")
    print(f"{'─'*62}")
